language: node_js
node_js:
  - "10"

sudo: true
dist: trusty

branches:
  only:
    - master

before_script:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get update
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb

jobs:
  include:
    - stage: Prepare environment
      script:
        - cd bogenliga
        - npm ci
        - npm install
    - stage: Run syntax check (tslint)
      script:
        - cd bogenliga
        - npm run lint
    - stage: Test application
      script:
        - cd bogenliga
        #- ng test --watch false
        #- npm run e2e
        - echo "Skip tests"
    - stage: Build application
      script:
        - cd bogenliga
        - ng build --configuration=offline --base-href "https://exxcellent.github.io/swt2-bsa-frontend"
    - stage: Deploy to github
      script:
        - cd bogenliga
      # DEPLOY GITHUB PAGES
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
        local_dir: dist/swt2-bsa-frontend
        verbose: true
        keep-history: true
        on:
          branch: master

stages:
  - prepare
  - tslint
  - test
  - build
  - deploy
